name: groestlcoin-core
version: '26.0'
summary: Fully validating Groestlcoin peer-to-peer network node, wallet and GUI
description: |
  Groestlcoin Core connects to the Groestlcoin peer-to-peer network to download and
  fully validate blocks and transactions. It also includes a wallet and
  graphical user interface.

grade: stable
confinement: strict
base: core18

apps:
  daemon:
    command: groestlcoind
    plugs: [home,removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at
      # ~/snap/groestlcoin-core/common/.groestlcoin/ instead of
      # ~/snap/groestlcoin-core/current/.groestlcoin/, and each new version of the
      # snap won't have a different data directory:
      # https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch groestlcoin-qt
    plugs: [home,removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: groestlcoin-cli
    plugs: [home,removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: groestlcoin-tx
    environment:
      HOME: $SNAP_USER_COMMON
  wallet:
    command: groestlcoin-wallet
    plugs: [home, removable-media]
    environment:
      HOME: $SNAP_USER_COMMON
  util:
    command: groestlcoin-util
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  # Needed to supply desktop-launch
  # Paste from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  # Boilerplate seems to be required according to https://bugs.launchpad.net/snapcraft/+bug/1800057
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  groestlcoin-core:
    plugin: nil
    override-build: |
      env | grep SNAP
      wget https://github.com/Groestlcoin/groestlcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/SHA256SUMS
      wget https://github.com/Groestlcoin/groestlcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/groestlcoin-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      wget https://github.com/Groestlcoin/groestlcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/groestlcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      echo "ebf227f6714f490e6a40c96e80c8c8cae1b7b5e49c69733f4d014456f46238d9  SHA256SUMS" | sha256sum --check
      sha256sum --ignore-missing --check SHA256SUMS
      tar -xvf groestlcoin-${SNAPCRAFT_PROJECT_VERSION}-${SNAPCRAFT_ARCH_TRIPLET}.tar.gz
      tar -xvf groestlcoin-${SNAPCRAFT_PROJECT_VERSION}.tar.gz
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin groestlcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/groestlcoind
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin groestlcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/groestlcoin-qt
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin groestlcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/groestlcoin-cli
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin groestlcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/groestlcoin-tx
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin groestlcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/groestlcoin-wallet
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin groestlcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/groestlcoin-util
      wget https://raw.githubusercontent.com/Groestlcoin/groestlcoin/v${SNAPCRAFT_PROJECT_VERSION}/share/pixmaps/groestlcoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps groestlcoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
